### ISSUE TITLE
Should comment the code when adding a headerfile

### ISSUE THREAD

**Issue by squeedee** [scothis/dies#49]
We have a boilerplate already, and it's passed to [addlicense](https://github.com/google/addlicense) which expects plain text, and adds comment characters as needed. 

To maintain compatibility with existing headerfiles, it'd be nice if dies added the comment characters also.

**Comment by scothis** [comment]
While a best practice, there's no need to specify a header file.

Instead of:
```
diegen die:headerFile="hack/boilerplate.go.txt" paths="./..."
```

run
```
diegen die paths="./..."
```

You do need to specify `die` which comes from our use of controller-gen as a starting point, although it's a bit strange in this context as it's the only command.

**Comment by scothis** [comment]
Please reopen if this doesn't solve your need.
